repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
-   repo: https://github.com/adrienverge/yamllint
    rev: v1.19.0
    hooks:
    -   id: yamllint
-   repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.26.1
    hooks:
    -   id: cfn-python-lint
        files: templates/.*\.(json|yml|yaml)$
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    -   id: remove-tabs
